version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
#  frontend:
#    container_name: frontend
#    image: bidoubletwice/foodgram_frontend
#    command: cp -r /app/build/. /static/
#    volumes:
#      - static:/static/

  db:
    container_name: db
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    container_name: backend
    image: bidoubletwice/foodgram_backend
    restart: always
    volumes:
      - static:/static/
      - media:/media/
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    container_name: nginx
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
#  nginx:
#    container_name: nginx
#    image: bidoubletwice/foodgram_gateway
#    restart: always
#    ports:
#      - '80:80'
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - ../frontend/build:/usr/share/nginx/html/
#      - ../docs/:/usr/share/nginx/html/api/docs/
#      - static:/static/
#      - media:/media/
#    depends_on:
#      - backend
