version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: bidoubletwice/foodgram_backend
    restart: always
    env_file: .env
#    env_file: ../backend/.env
    depends_on:
      - db
    volumes:
      - static:/static/
      - media:/media/
  frontend:
    image: bidoubletwice/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static/
  gateway:
    image: bidoubletwice/foodgram_gateway
    env_file: .env
#    env_file: ../backend/.env
    volumes:
      - static:/static/
      - media:/media/
    ports:
      - 8000:80
    depends_on:
      - backend