# Project Settings
PAGE_SIZE = 6

# Recipe
MAX_LENGTH_RECIPE_NAME = 200
MAX_LENGTH_INGREDIENT_NAME = 100
MAX_LENGTH_INGREDIENT_M_UNIT = 50
MAX_LENGTH_TAG_NAME = 200
MAX_LENGTH_TAG_COLOR = 7
MAX_LENGTH_TAG_SLUG = 200
MIN_COOKING_TIME = 1

# User
MAX_LENGTH_USER_CHARFIELD = 150
MAX_LENGTH_USER_EMAIL = 254
