# Project Settings
PAGE_SIZE = 6

# Recipe Models
MAX_LENGTH_RECIPE_NAME = 200
MAX_LENGTH_INGREDIENT_NAME = 100
MAX_LENGTH_INGREDIENT_M_UNIT = 50
MAX_LENGTH_TAG_NAME = 200
MAX_LENGTH_TAG_COLOR = 7
MAX_LENGTH_TAG_SLUG = 200

# User Models
MAX_LENGTH_USER_USERNAME = 150
MAX_LENGTH_USER_EMAIL = 254
MAX_LENGTH_USER_NAME = 150

# Recipe serializers
MIN_COOKING_TIME = 0
