# Generated by Django 3.2.20 on 2023-10-29 15:26

from django.db import migrations, models
import foodgram.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(help_text='Введите единицу измерения', max_length=50, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Укажите значение в минутах', validators=[foodgram.validators.validate_positive_small_integer], verbose_name='Время приготовления'),
        ),
    ]
